name: Update TAPI Journey Data

on:
  schedule:
    # Runs 8 times every day at the requested times (in UTC).
    # Requested times: 6:30, 6:40, 6:50, 6:55, 7:00, 7:05, 7:10, 7:15
    # Be sure these UTC times match your local (BST/GMT) needs!
    - cron: "30,40,50,55 6 * * * "
    - cron: "0,5,10,15 7 * * * "
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run TAPI data update script
        run: python update_journey_data.py
        env:
          # developer.transportapi.com API credentials 
          TAPI_APP_ID: ${{ secrets.TAPI_APP_ID }}
          TAPI_APP_KEY: ${{ secrets.TAPI_APP_KEY }}

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "AUTO: Update TAPI journey data"
          file_pattern: live_data.json
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com


