name: Update Live Rail Data

on:
  # Allows manual runs from the GitHub Actions UI
  workflow_dispatch:
  # Also runs on push to main branch
  push:
    branches:
      - main
  
  # Scheduled runs (all times are in UTC; BST is UTC+1)
  schedule:
    # Weekday runs (Mon-Fri) - 8 runs between 6:30 and 7:15 AM BST
    - cron: '30 05 * * 1-5' # 06:30 BST (05:30 UTC)
    - cron: '40 05 * * 1-5' # 06:40 BST (05:40 UTC)
    - cron: '50 05 * * 1-5' # 06:50 BST (05:50 UTC)
    - cron: '55 05 * * 1-5' # 06:55 BST (05:55 UTC)
    - cron: '00 06 * * 1-5' # 07:00 BST (06:00 UTC)
    - cron: '05 06 * * 1-5' # 07:05 BST (06:05 UTC)
    - cron: '10 06 * * 1-5' # 07:10 BST (06:10 UTC)
    - cron: '15 06 * * 1-5' # 07:15 BST (06:15 UTC)
    # Weekend runs (Sat/Sun) to check direct service logic
    - cron: '30 06 * * 6,0' # 07:30 BST (06:30 UTC) for weekends

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      # Install zeep (for Darwin SOAP) and requests (for robust HTTP transport)
      run: |
        python -m pip install --upgrade pip
        pip install zeep requests
        
    - name: Run data update script (using Darwin Token)
      # Pass the secrets securely as environment variables
      env:
        DARWIN_TOKEN: ${{ secrets.DARWIN_TOKEN }}
        TAPI_APP_ID: ${{ secrets.TAPI_APP_ID }}
        TAPI_APP_KEY: ${{ secrets.TAPI_APP_KEY }}
      run: python update_journey_data.py
      
    - name: Commit files
      # Commit the updated live_data.json file back to the repository
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add live_data.json
        git commit -m "Automated update of live rail data (Darwin)" || echo "No changes to commit"
        git push









